services:
  app:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      - PORT=3003
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=findyourdoctor

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=findyourdoctor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: